services:
  - type: web
    name: axion-backend
    runtime: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4